'use client'

import { useEffect, useMemo, useRef, useState } from 'react'
import type { MouseEvent } from 'react'
import { MousePointer2 } from 'lucide-react'
import { useMutation, useQuery } from '@apollo/client/react'
import { DAY_VIEW_SLOT_MINUTES, SLOT_MINUTES, WORK_DAYS } from '@/app/dashboard/_lib/scheduler-constants'
import { addDays, formatMonthDayLabel, formatWeekdayName, getMonthDays, getMonthStart, getWeekStart, isDateBefore, toIsoDate } from '@/app/dashboard/_lib/scheduler-date-utils'
import { buildMonthSummaries, createMonthFilterTotals, getWeekDates, shouldRenderTimelineEvent } from '@/app/dashboard/_lib/scheduler-event-utils'
import { buildLocalEvent, createDefaultForm, createFormFromEvent, createSchedulerMutationInput, getSelectionForEvent } from '@/app/dashboard/_lib/scheduler-form-utils'
import { CREATE_SCHEDULE_EVENT, DELETE_SCHEDULE_EVENT, GET_SCHEDULER_DATA, UPDATE_SCHEDULE_EVENT } from '@/app/dashboard/_lib/scheduler-queries'
import { normalizeTimelineTime, timeToMinutes } from '@/app/dashboard/_lib/scheduler-time-utils'
import type { DraftForm, MonthViewFilter, SchedulerQueryResult, SchedulerViewMode, Selection } from '@/app/dashboard/_lib/scheduler-types'
import { SchedulerCalendarSidebar } from '@/app/dashboard/_components/scheduler-calendar-sidebar'
import { SchedulerDayView } from '@/app/dashboard/_components/scheduler-day-view'
import { SchedulerEventDialog } from '@/app/dashboard/_components/scheduler-event-dialog'
import { SchedulerLegend } from '@/app/dashboard/_components/scheduler-legend'
import { SchedulerMonthSummaryView } from '@/app/dashboard/_components/scheduler-month-summary-view'
import { SchedulerToolbar } from '@/app/dashboard/_components/scheduler-toolbar'
import { SchedulerWeekView } from '@/app/dashboard/_components/scheduler-week-view'
import { YearRoadmapPlaceholder } from '@/app/dashboard/_components/year-roadmap-placeholder'
import { Badge } from '@/components/ui/badge'
import { Tabs } from '@/components/ui/tabs'
import type { ScheduleEvent } from '@/lib/types'
import { cn } from '@/lib/utils'

export function AdminScheduler() {
  const [weekStart, setWeekStart] = useState(() => getWeekStart(new Date())); const [calendarMonth, setCalendarMonth] = useState(() => getMonthStart(new Date())); const [viewMode, setViewMode] = useState<SchedulerViewMode>('week'); const [focusedDate, setFocusedDate] = useState(() => { const today = new Date(); today.setHours(0, 0, 0, 0); return today }); const [weekMotionClass, setWeekMotionClass] = useState('opacity-100 translate-x-0 scale-100'); const [selection, setSelection] = useState<Selection | null>(null); const [isDragging, setIsDragging] = useState(false); const [dialogOpen, setDialogOpen] = useState(false); const [form, setForm] = useState<DraftForm | null>(null); const [editingEvent, setEditingEvent] = useState<ScheduleEvent | null>(null); const [localEvents, setLocalEvents] = useState<ScheduleEvent[]>([]); const [mutationError, setMutationError] = useState<string | null>(null); const [selectedRoomTab, setSelectedRoomTab] = useState('all'); const [monthFilter, setMonthFilter] = useState<MonthViewFilter>('all')
  const { data, loading, error, refetch } = useQuery<SchedulerQueryResult>(GET_SCHEDULER_DATA); const [createScheduleEvent, { loading: saving }] = useMutation(CREATE_SCHEDULE_EVENT); const [updateScheduleEvent, { loading: updating }] = useMutation(UPDATE_SCHEDULE_EVENT); const [deleteScheduleEvent, { loading: deleting }] = useMutation(DELETE_SCHEDULE_EVENT)
  const rooms = useMemo(() => [...(data?.rooms ?? [])].sort((left, right) => left.number.localeCompare(right.number, 'mn', { numeric: true })), [data?.rooms]); const roomLookup = useMemo(() => new Map(rooms.map((room) => [room.id, room] as const)), [rooms]); const events = useMemo(() => [...(data?.events ?? []), ...localEvents].filter(shouldRenderTimelineEvent), [data?.events, localEvents]); const weekDates = useMemo(() => getWeekDates(weekStart), [weekStart]); const monthDays = useMemo(() => getMonthDays(calendarMonth), [calendarMonth]); const focusedDateLabel = useMemo(() => new Intl.DateTimeFormat('mn-MN', { month: '2-digit', day: '2-digit', weekday: 'long' }).format(focusedDate), [focusedDate]); const focusedDateTitle = useMemo(() => `${formatWeekdayName(focusedDate)} · ${formatMonthDayLabel(focusedDate)}`, [focusedDate]); const focusedDateIso = useMemo(() => toIsoDate(focusedDate), [focusedDate]); const focusedDayOfWeek = useMemo(() => focusedDate.getDay() === 0 ? 7 : focusedDate.getDay(), [focusedDate]); const selectedRoomView = useMemo(() => selectedRoomTab === 'all' ? null : rooms.find((room) => room.id === selectedRoomTab) ?? null, [rooms, selectedRoomTab]); const roomsForFocusedView = useMemo(() => selectedRoomView ? [selectedRoomView] : rooms, [rooms, selectedRoomView]); const scopedRoomIds = useMemo(() => new Set(roomsForFocusedView.map((room) => room.id)), [roomsForFocusedView]); const monthSummaries = useMemo(() => buildMonthSummaries(calendarMonth, events, monthDays, roomLookup, scopedRoomIds), [calendarMonth, events, monthDays, roomLookup, scopedRoomIds]); const monthFilterTotals = useMemo(() => createMonthFilterTotals(monthSummaries), [monthSummaries]); const selectedRoom = selection ? rooms.find((room) => room.id === selection.roomId) : null; const selectedDay = selection ? WORK_DAYS.find((day) => day.value === selection.dayOfWeek) : null; const selectedDayName = selection ? formatWeekdayName(addDays(weekStart, selection.dayOfWeek - 1)) : null
  const previousWeekStartRef = useRef(weekStart)

  useEffect(() => { const previous = previousWeekStartRef.current; if (previous.getTime() === weekStart.getTime()) return; setWeekMotionClass(isDateBefore(previous, weekStart) ? 'opacity-0 translate-x-10 scale-[0.985]' : 'opacity-0 -translate-x-10 scale-[0.985]'); const frameId = requestAnimationFrame(() => setWeekMotionClass('opacity-100 translate-x-0 scale-100')); previousWeekStartRef.current = weekStart; return () => cancelAnimationFrame(frameId) }, [weekStart])
  useEffect(() => { if (selectedRoomTab !== 'all' && !rooms.some((room) => room.id === selectedRoomTab)) setSelectedRoomTab('all') }, [rooms, selectedRoomTab])

  const updateWeekStart = (date: Date) => { const normalizedDate = new Date(date); normalizedDate.setHours(0, 0, 0, 0); const nextWeekStart = getWeekStart(date); setWeekStart(nextWeekStart); setCalendarMonth(getMonthStart(nextWeekStart)); setFocusedDate(normalizedDate) }
  const openCreateDialog = (targetSelection = selection) => { const fallbackSelection = rooms[0] ? { roomId: rooms[0].id, dayOfWeek: viewMode === 'day' ? focusedDayOfWeek : WORK_DAYS[0].value, startSlot: 0, endSlot: 1, slotMinutes: viewMode === 'day' ? DAY_VIEW_SLOT_MINUTES : SLOT_MINUTES } : null; const nextSelection = targetSelection ?? fallbackSelection; if (!nextSelection) return; setSelection(nextSelection); setForm(createDefaultForm(nextSelection, weekStart)); setEditingEvent(null); setMutationError(null); setDialogOpen(true) }
  const openEditDialog = (event: ScheduleEvent, roomId: string, dayOfWeek: number) => { setSelection(getSelectionForEvent(event, roomId, dayOfWeek, viewMode)); setForm(createFormFromEvent(event, dayOfWeek, weekStart)); setEditingEvent(event); setMutationError(null); setDialogOpen(true) }
  const handlePointerDown = (roomId: string, dayOfWeek: number, slot: number, slotMinutes: number, button: number) => { if (button !== 0) return; setSelection({ roomId, dayOfWeek, startSlot: slot, endSlot: slot, slotMinutes }); setIsDragging(true) }
  const handlePointerEnter = (roomId: string, dayOfWeek: number, slot: number) => setSelection((current) => !isDragging || !current || current.roomId !== roomId || current.dayOfWeek !== dayOfWeek ? current : { ...current, endSlot: slot })
  const handleContextMenu = (event: MouseEvent, roomId: string, dayOfWeek: number, slot: number, slotMinutes: number) => { event.preventDefault(); openCreateDialog(selection?.roomId === roomId && selection.dayOfWeek === dayOfWeek ? selection : { roomId, dayOfWeek, startSlot: slot, endSlot: slot, slotMinutes }) }
  const handleSave = async () => { if (!selection || !form || !form.title.trim()) return; if (timeToMinutes(normalizeTimelineTime(form.endTime)) <= timeToMinutes(normalizeTimelineTime(form.startTime))) return setMutationError('Дуусах цаг эхлэх цагаас хойш байх ёстой.'); const input = createSchedulerMutationInput(selection.roomId, selection.dayOfWeek, form); try { setMutationError(null); if (editingEvent?.id.startsWith('local-')) setLocalEvents((current) => current.map((event) => event.id === editingEvent.id ? { ...buildLocalEvent(selection.roomId, selection.dayOfWeek, form), id: editingEvent.id } : event)); else if (editingEvent) await updateScheduleEvent({ variables: { id: editingEvent.id, input } }); else await createScheduleEvent({ variables: { input } }); await refetch(); setDialogOpen(false); setSelection(null); setEditingEvent(null) } catch (saveError) { if (editingEvent) return setMutationError(saveError instanceof Error ? saveError.message : 'Хуваарь хадгалж чадсангүй'); setLocalEvents((current) => [...current, buildLocalEvent(selection.roomId, selection.dayOfWeek, form)]); setMutationError(saveError instanceof Error ? saveError.message : 'Хуваарь хадгалж чадсангүй'); setDialogOpen(false); setSelection(null); setEditingEvent(null) } }
  const handleDelete = async () => { if (!editingEvent) return; try { setMutationError(null); if (editingEvent.id.startsWith('local-')) setLocalEvents((current) => current.filter((event) => event.id !== editingEvent.id)); else { await deleteScheduleEvent({ variables: { id: editingEvent.id } }); await refetch() } setDialogOpen(false); setSelection(null); setEditingEvent(null) } catch (deleteError) { setMutationError(deleteError instanceof Error ? deleteError.message : 'Хуваарь устгаж чадсангүй') } }

  return (
    <section className={cn('space-y-4 transition-[padding-right] duration-200', dialogOpen ? 'xl:pr-[26rem]' : 'pr-0')} onPointerUp={() => setIsDragging(false)} onPointerLeave={() => setIsDragging(false)}>
      <div className="rounded-md border border-[#d1d1d1] bg-white shadow-sm dark:border-border dark:bg-card"><Tabs value={selectedRoomTab} onValueChange={setSelectedRoomTab} className="gap-0"><SchedulerToolbar rooms={rooms} setViewMode={setViewMode} viewMode={viewMode} /><div className="grid items-stretch gap-3 p-3 xl:grid-cols-[212px_minmax(0,1fr)]"><SchedulerCalendarSidebar calendarMonth={calendarMonth} focusedDate={focusedDate} isCalendarOpen monthDays={monthDays} onSelectDay={updateWeekStart} onToday={() => updateWeekStart(new Date())} setCalendarMonth={setCalendarMonth} viewMode={viewMode} weekStart={weekStart} /><div className={cn('h-full min-w-0 overflow-hidden rounded-2xl border border-[#e8e8eb] bg-white shadow-sm transition-all duration-500 ease-out dark:border-border dark:bg-card', weekMotionClass)}><div className="h-full overflow-auto">{viewMode === 'week' ? <SchedulerWeekView errorMessage={error?.message} events={events} loading={loading && !data} onContextMenu={handleContextMenu} onEditEvent={openEditDialog} onPointerDown={handlePointerDown} onPointerEnter={handlePointerEnter} rooms={rooms} selectedRoomTab={selectedRoomTab} selectedRoomView={selectedRoomView} selection={selection} weekDates={weekDates} /> : viewMode === 'day' ? <SchedulerDayView errorMessage={error?.message} events={events} focusedDateIso={focusedDateIso} focusedDateLabel={focusedDateLabel} focusedDateTitle={focusedDateTitle} focusedDayOfWeek={focusedDayOfWeek} loading={loading && !data} onContextMenu={handleContextMenu} onEditEvent={openEditDialog} onPointerDown={handlePointerDown} onPointerEnter={handlePointerEnter} rooms={roomsForFocusedView} selection={selection} /> : viewMode === 'month' ? <SchedulerMonthSummaryView calendarMonth={calendarMonth} focusedDate={focusedDate} monthSummaries={monthSummaries} monthFilter={monthFilter} monthFilterTotals={monthFilterTotals} onFilterChange={setMonthFilter} onSelectDate={(date) => { updateWeekStart(date); setViewMode('day') }} selectedRoomView={selectedRoomView} /> : <YearRoadmapPlaceholder />}</div></div></div></Tabs></div>
      <div className="flex flex-wrap items-center gap-2 text-xs text-muted-foreground"><MousePointer2 className="h-3.5 w-3.5" /><SchedulerLegend color="bg-[#2564cf]" label="Элсэлт" /><SchedulerLegend color="bg-[#7f5ccf]" label="Клуб" /><SchedulerLegend color="bg-[#d83b01]" label="Event" />{mutationError && <Badge variant="outline" className="text-destructive">{mutationError}</Badge>}</div>
      <SchedulerEventDialog deleting={deleting} dialogOpen={dialogOpen} editingEvent={editingEvent} form={form} mutationError={mutationError} onDelete={handleDelete} onOpenChange={setDialogOpen} onSave={handleSave} saving={saving} selectedDayLabel={selectedDay?.label ?? null} selectedDayName={selectedDayName} selectedRoom={selectedRoom ?? null} setForm={setForm} updating={updating} />
    </section>
  )
}
