'use client'

import { CALENDAR_DAY_LETTERS } from '@/app/dashboard/_lib/scheduler-constants'
import { formatMonthLabel, isSameDate } from '@/app/dashboard/_lib/scheduler-date-utils'
import { getEventLabel, getEventTone } from '@/app/dashboard/_lib/scheduler-event-utils'
import type { MonthSummary, MonthViewFilter } from '@/app/dashboard/_lib/scheduler-types'
import type { Room } from '@/lib/types'
import { cn } from '@/lib/utils'

export function SchedulerMonthSummaryView({ calendarMonth, focusedDate, monthSummaries, monthFilter, monthFilterTotals, onFilterChange, onSelectDate, selectedRoomView }: { calendarMonth: Date; focusedDate: Date; monthSummaries: MonthSummary[]; monthFilter: MonthViewFilter; monthFilterTotals: Record<MonthViewFilter, number>; onFilterChange: (_filter: MonthViewFilter) => void; onSelectDate: (_date: Date) => void; selectedRoomView: Room | null }) {
  const filterOptions: Array<{ key: MonthViewFilter; label: string }> = [{ key: 'all', label: 'All' }, { key: 'class', label: 'Classes' }, { key: 'club', label: 'Clubs' }, { key: 'closed', label: 'Closed' }]

  return (
    <div className="min-w-0">
      <div className="border-b border-[#e1dfdd] px-4 py-3 dark:border-border"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-sm font-semibold text-foreground">{formatMonthLabel(calendarMonth)} summary</p><p className="text-xs text-muted-foreground">{selectedRoomView ? `${selectedRoomView.number} ангийн харагдац` : 'Бүх ангийн сарын тойм'}</p></div><div className="flex flex-wrap items-center gap-2">{filterOptions.map((option) => <button key={option.key} type="button" className={cn('inline-flex items-center gap-2 rounded-full border px-3 py-1.5 text-xs font-medium transition', monthFilter === option.key ? 'border-[#6264a7] bg-[#eef0ff] text-[#323769] dark:border-[#8f93ff] dark:bg-[#252b45] dark:text-white' : 'border-[#d9dbea] bg-white text-muted-foreground hover:border-[#bec2e5] hover:text-foreground dark:border-[#30364d] dark:bg-[#171b27] dark:hover:text-white')} onClick={() => onFilterChange(option.key)}><span>{option.label}</span><span className="rounded-full bg-black/5 px-1.5 py-0.5 text-[10px] dark:bg-white/10">{monthFilterTotals[option.key]}</span></button>)}</div></div></div>
      <div className="grid grid-cols-7 border-b border-[#e1dfdd] bg-[#faf9f8] text-xs font-semibold uppercase tracking-wide text-muted-foreground dark:border-border dark:bg-muted/20">{CALENDAR_DAY_LETTERS.map((letter, index) => <div key={`${letter}-${index}`} className="border-r border-[#ececf4] px-3 py-2 last:border-r-0 dark:border-border/60">{letter}</div>)}</div>
      <div className="grid grid-cols-7">{monthSummaries.map((summary) => { const visibleOccurrences = monthFilter === 'all' ? summary.occurrences : summary.occurrences.filter((occurrence) => occurrence.event.type === monthFilter); const previewOccurrences = visibleOccurrences.slice(0, 2); const extraCount = Math.max(0, visibleOccurrences.length - previewOccurrences.length); const isToday = isSameDate(summary.date, new Date()); const isFocused = isSameDate(summary.date, focusedDate); return <button key={summary.dateIso} type="button" className={cn('min-h-[152px] border-b border-r border-[#ececf4] p-3 text-left align-top transition hover:bg-[#f8f9ff] dark:border-border/60 dark:hover:bg-[#1d2131]', summary.isWeekend && 'bg-[#fafbff] dark:bg-[#161a27]', !summary.isCurrentMonth && 'bg-[#fcfcfe] text-muted-foreground/55 dark:bg-[#111522] dark:text-muted-foreground/55', summary.counts.closed > 0 && summary.isCurrentMonth && 'bg-[#fff9ec] dark:bg-[#2b2414]', isFocused && 'ring-2 ring-inset ring-[#6264a7]', isToday && 'outline outline-1 outline-[#a8ace6] outline-offset-[-2px]')} onClick={() => onSelectDate(summary.date)}><div className="mb-2 flex items-start justify-between gap-2"><div><div className="text-sm font-semibold text-foreground dark:text-white">{summary.date.getDate()}</div>{summary.totalCount > 0 && <div className="mt-1 text-[11px] text-muted-foreground">{summary.totalCount} schedule</div>}</div><div className="flex items-center gap-1">{summary.hasConflict && <span className="h-2.5 w-2.5 rounded-full bg-[#d83b01]" title="Conflict detected" />}{summary.totalCount > 0 && <span className="rounded-full bg-[#eef0ff] px-1.5 py-0.5 text-[10px] font-semibold text-[#323769] dark:bg-[#252b45] dark:text-white">{visibleOccurrences.length}</span>}</div></div><div className="mb-2 flex flex-wrap gap-1">{summary.counts.class > 0 && <span className="rounded-full bg-[#eaf2ff] px-1.5 py-0.5 text-[10px] font-medium text-[#17375e]">{summary.counts.class} class</span>}{summary.counts.club > 0 && <span className="rounded-full bg-[#f1ecff] px-1.5 py-0.5 text-[10px] font-medium text-[#3f2a76]">{summary.counts.club} club</span>}{summary.counts.closed > 0 && <span className="rounded-full bg-[#fff4ce] px-1.5 py-0.5 text-[10px] font-medium text-[#5d2d00]">{summary.counts.closed} closed</span>}</div><div className="space-y-1.5">{previewOccurrences.map(({ event, room }) => <div key={`${summary.dateIso}-${event.id}-${room?.id ?? 'room'}`} className={cn('rounded-lg border px-2 py-1.5 text-[11px] shadow-sm', getEventTone(event.type))}><div className="truncate font-semibold">{event.title}</div><div className="truncate opacity-80">{event.startTime} · {selectedRoomView ? getEventLabel(event.type) : `${room?.number ?? ''} · ${getEventLabel(event.type)}`}</div></div>)}{extraCount > 0 && <div className="text-[11px] font-medium text-muted-foreground">+{extraCount} more</div>}</div></button> })}</div>
    </div>
  )
}
