ALTER TABLE clubs ADD COLUMN created_by TEXT NOT NULL DEFAULT '';
ALTER TABLE clubs ADD COLUMN interest_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE clubs ADD COLUMN member_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE clubs ADD COLUMN grade_range TEXT NOT NULL DEFAULT '';
ALTER TABLE clubs ADD COLUMN allowed_days TEXT NOT NULL DEFAULT '';
ALTER TABLE clubs ADD COLUMN start_date TEXT NOT NULL DEFAULT '';
ALTER TABLE clubs ADD COLUMN end_date TEXT NOT NULL DEFAULT '';
ALTER TABLE clubs ADD COLUMN note TEXT NOT NULL DEFAULT '';
ALTER TABLE clubs ADD COLUMN verified INTEGER NOT NULL DEFAULT 0;

ALTER TABLE club_requests ADD COLUMN student_limit INTEGER NOT NULL DEFAULT 20;
ALTER TABLE club_requests ADD COLUMN grade_range TEXT NOT NULL DEFAULT '';
ALTER TABLE club_requests ADD COLUMN allowed_days TEXT NOT NULL DEFAULT '';
ALTER TABLE club_requests ADD COLUMN start_date TEXT NOT NULL DEFAULT '';
ALTER TABLE club_requests ADD COLUMN end_date TEXT NOT NULL DEFAULT '';
ALTER TABLE club_requests ADD COLUMN club_status TEXT NOT NULL DEFAULT 'pending';
ALTER TABLE club_requests ADD COLUMN flagged_reason TEXT;
ALTER TABLE club_requests ADD COLUMN created_by TEXT NOT NULL DEFAULT '';

ALTER TABLE users ADD COLUMN reason TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN last_active TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN club_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN notes TEXT NOT NULL DEFAULT '';
