import type { ScheduleRow } from '@/db/schema'
import { FIXTURE_CREATED_AT } from '@/lib/timeline-seed-shared'

export const seedSchedules: ScheduleRow[] = [
  {
    id: 'schedule-physics-101',
    roomId: 'room-301',
    title: 'Physics 101',
    type: 'class',
    daysOfWeek: JSON.stringify([1, 3, 5]),
    startTime: '08:00',
    endTime: '09:30',
    instructor: 'Ariun Admin',
    notes: 'Core first-year lecture block.',
    startDate: '2026-01-12',
    endDate: '2026-12-18',
    createdBy: 'admin-1',
    createdAt: FIXTURE_CREATED_AT,
  },
  {
    id: 'schedule-advanced-math',
    roomId: 'room-401',
    title: 'Advanced Mathematics',
    type: 'class',
    daysOfWeek: JSON.stringify([1, 3, 5]),
    startTime: '13:00',
    endTime: '14:30',
    instructor: 'Ariun Admin',
    notes: 'Admin-owned sample schedule for dashboard filtering.',
    startDate: '2026-01-12',
    endDate: '2026-12-18',
    createdBy: 'admin-1',
    createdAt: FIXTURE_CREATED_AT,
  },
  {
    id: 'schedule-robotics-club',
    roomId: 'room-303',
    title: 'Robotics Club',
    type: 'club',
    daysOfWeek: JSON.stringify([2, 4]),
    startTime: '15:30',
    endTime: '17:00',
    instructor: 'Enkhmaa Mentor',
    notes: 'Hands-on robotics club session.',
    startDate: '2026-01-12',
    endDate: '2026-12-18',
    createdBy: 'admin-1',
    createdAt: FIXTURE_CREATED_AT,
  },
  {
    id: 'schedule-debate-society',
    roomId: 'room-402',
    title: 'Debate Society',
    type: 'club',
    daysOfWeek: JSON.stringify([3, 5]),
    startTime: '16:00',
    endTime: '17:30',
    instructor: 'Temuulen Coach',
    notes: 'Large-room student club booking.',
    startDate: '2026-01-12',
    endDate: '2026-12-18',
    createdBy: 'admin-1',
    createdAt: FIXTURE_CREATED_AT,
  },
  {
    id: 'schedule-programming-403',
    roomId: 'room-403',
    title: 'Programming Workshop',
    type: 'class',
    daysOfWeek: JSON.stringify([1, 4]),
    startTime: '11:00',
    endTime: '12:30',
    instructor: 'Ariun Admin',
    notes: 'Project-based programming workshop.',
    startDate: '2026-01-12',
    endDate: '2026-12-18',
    createdBy: 'admin-1',
    createdAt: FIXTURE_CREATED_AT,
  },
]
