import type { Employee, Document, AuditLogEntry, Job } from './types'

export const mockEmployees: Employee[] = [
  {
    id: 'emp-001',
    employeeCode: 'EMP-2024-001',
    firstName: 'สมชาย',
    lastName: 'ใจดี',
    firstNameEng: 'Somchai',
    lastNameEng: 'Jaidee',
    department: 'Engineering',
    branch: 'Bangkok HQ',
    level: 'Senior',
    hireDate: '2024-01-15',
    numberOfVacationDays: 15,
    terminationDate: null,
    status: 'active',
    email: 'somchai.j@company.com',
  },
  {
    id: 'emp-002',
    employeeCode: 'EMP-2024-002',
    firstName: 'สมหญิง',
    lastName: 'รักงาน',
    firstNameEng: 'Somying',
    lastNameEng: 'Rukngarn',
    department: 'HR',
    branch: 'Bangkok HQ',
    level: 'Manager',
    hireDate: '2024-02-01',
    numberOfVacationDays: 18,
    terminationDate: null,
    status: 'active',
    email: 'somying.r@company.com',
  },
]

export const mockDocuments: Document[] = [
  {
    id: 'doc-001',
    filename: 'Employment_Contract_Somchai_2024.pdf',
    action: 'add_employee',
    employeeId: 'emp-001',
    employeeName: 'Somchai Jaidee',
    generatedDate: '2024-01-15T09:30:00Z',
    fileType: 'pdf',
    status: 'success',
    phase: 'onboarding',
    signedUrlExpiry: '2024-01-16T09:30:00Z',
    storagePath: '/employees/emp-001/onboarding/2024-01-15/employment_contract.pdf',
  },
  {
    id: 'doc-002',
    filename: 'Probation_Order_Somchai_2024.pdf',
    action: 'add_employee',
    employeeId: 'emp-001',
    employeeName: 'Somchai Jaidee',
    generatedDate: '2024-01-15T09:31:00Z',
    fileType: 'pdf',
    status: 'success',
    phase: 'onboarding',
    signedUrlExpiry: '2024-01-16T09:31:00Z',
    storagePath: '/employees/emp-001/onboarding/2024-01-15/probation_order.pdf',
  },
  {
    id: 'doc-003',
    filename: 'Job_Description_Somchai_2024.pdf',
    action: 'add_employee',
    employeeId: 'emp-001',
    employeeName: 'Somchai Jaidee',
    generatedDate: '2024-01-15T09:32:00Z',
    fileType: 'pdf',
    status: 'success',
    phase: 'onboarding',
    signedUrlExpiry: '2024-01-16T09:32:00Z',
    storagePath: '/employees/emp-001/onboarding/2024-01-15/job_description.pdf',
  },
  {
    id: 'doc-004',
    filename: 'NDA_Somchai_2024.pdf',
    action: 'add_employee',
    employeeId: 'emp-001',
    employeeName: 'Somchai Jaidee',
    generatedDate: '2024-01-15T09:33:00Z',
    fileType: 'pdf',
    status: 'success',
    phase: 'onboarding',
    signedUrlExpiry: '2024-01-16T09:33:00Z',
    storagePath: '/employees/emp-001/onboarding/2024-01-15/nda.pdf',
  },
]

export const mockAuditLogs: AuditLogEntry[] = [
  {
    id: 'audit-001',
    timestamp: '2024-01-15T09:30:00Z',
    employeeId: 'emp-001',
    employeeName: 'Somchai Jaidee',
    action: 'add_employee',
    documentsCount: 4,
    recipientsNotified: ['hr_team', 'department_chief', 'branch_manager'],
    triggerSource: 'webhook',
    status: 'success',
    retryCount: 0,
    changedFields: ['status', 'hireDate', 'department'],
    storagePaths: ['/employees/emp-001/onboarding/2024-01-15/'],
    failureReason: null,
  },
  {
    id: 'audit-002',
    timestamp: '2024-02-01T10:15:00Z',
    employeeId: 'emp-002',
    employeeName: 'Somying Rukngarn',
    action: 'add_employee',
    documentsCount: 4,
    recipientsNotified: ['hr_team', 'department_chief'],
    triggerSource: 'manual',
    status: 'success',
    retryCount: 0,
    changedFields: ['status', 'hireDate'],
    storagePaths: ['/employees/emp-002/onboarding/2024-02-01/'],
    failureReason: null,
  },
]

export const mockJobs: Job[] = [
  {
    id: 'job-001',
    action: 'add_employee',
    employeeId: 'emp-001',
    employeeName: 'Somchai Jaidee',
    status: 'success',
    createdAt: '2024-01-15T09:28:00Z',
    completedAt: '2024-01-15T09:35:00Z',
    documentsCount: 4,
    estimatedCompletion: '2024-01-15T09:35:00Z',
  },
  {
    id: 'job-002',
    action: 'add_employee',
    employeeId: 'emp-002',
    employeeName: 'Somying Rukngarn',
    status: 'processing',
    createdAt: '2024-02-01T10:10:00Z',
    completedAt: null,
    documentsCount: 4,
    estimatedCompletion: '2024-02-01T10:20:00Z',
  },
]
