import type { Employee, Document, AuditLogEntry, Job } from './types'

export const mockEmployees: Employee[] = [
  {
    id: 'emp-001',
    employeeCode: 'EMP-2024-001',
    firstName: 'Бат',
    lastName: 'Тэмүүлэн',
    firstNameEng: 'Бат',
    lastNameEng: 'Тэмүүлэн',
    department: 'Инженерчлэл',
    branch: 'Улаанбаатар төв',
    level: 'Ахлах',
    hireDate: '2024-01-15',
    numberOfVacationDays: 15,
    terminationDate: null,
    status: 'active',
    email: 'bat.t@company.com',
  },
  {
    id: 'emp-002',
    employeeCode: 'EMP-2024-002',
    firstName: 'Саруул',
    lastName: 'Эрдэнэ',
    firstNameEng: 'Саруул',
    lastNameEng: 'Эрдэнэ',
    department: 'Хүний нөөц',
    branch: 'Улаанбаатар төв',
    level: 'Менежер',
    hireDate: '2024-02-01',
    numberOfVacationDays: 18,
    terminationDate: null,
    status: 'active',
    email: 'saruul.e@company.com',
  },
]

export const mockDocuments: Document[] = [
  {
    id: 'doc-001',
    filename: 'Хөдөлмөрийн_гэрээ_Бат_2024.pdf',
    action: 'add_employee',
    employeeId: 'emp-001',
    employeeName: 'Бат Тэмүүлэн',
    generatedDate: '2024-01-15T09:30:00Z',
    fileType: 'pdf',
    status: 'success',
    phase: 'onboarding',
    signedUrlExpiry: '2024-01-16T09:30:00Z',
    storagePath: '/ажилтан/emp-001/ажилд-авах/2024-01-15/хөдөлмөрийн_гэрээ.pdf',
  },
  {
    id: 'doc-002',
    filename: 'Туршилтын_хугацааны_тушаал_Бат_2024.pdf',
    action: 'add_employee',
    employeeId: 'emp-001',
    employeeName: 'Бат Тэмүүлэн',
    generatedDate: '2024-01-15T09:31:00Z',
    fileType: 'pdf',
    status: 'success',
    phase: 'onboarding',
    signedUrlExpiry: '2024-01-16T09:31:00Z',
    storagePath:
      '/ажилтан/emp-001/ажилд-авах/2024-01-15/туршилтын_хугацааны_тушаал.pdf',
  },
  {
    id: 'doc-003',
    filename: 'Ажлын_байрны_тодорхойлолт_Бат_2024.pdf',
    action: 'add_employee',
    employeeId: 'emp-001',
    employeeName: 'Бат Тэмүүлэн',
    generatedDate: '2024-01-15T09:32:00Z',
    fileType: 'pdf',
    status: 'success',
    phase: 'onboarding',
    signedUrlExpiry: '2024-01-16T09:32:00Z',
    storagePath:
      '/ажилтан/emp-001/ажилд-авах/2024-01-15/ажлын_байрны_тодорхойлолт.pdf',
  },
  {
    id: 'doc-004',
    filename: 'Нууцлалын_гэрээ_Бат_2024.pdf',
    action: 'add_employee',
    employeeId: 'emp-001',
    employeeName: 'Бат Тэмүүлэн',
    generatedDate: '2024-01-15T09:33:00Z',
    fileType: 'pdf',
    status: 'success',
    phase: 'onboarding',
    signedUrlExpiry: '2024-01-16T09:33:00Z',
    storagePath: '/ажилтан/emp-001/ажилд-авах/2024-01-15/нууцлалын_гэрээ.pdf',
  },
]

export const mockAuditLogs: AuditLogEntry[] = [
  {
    id: 'audit-001',
    timestamp: '2024-01-15T09:30:00Z',
    employeeId: 'emp-001',
    employeeName: 'Бат Тэмүүлэн',
    action: 'add_employee',
    documentsCount: 4,
    recipientsNotified: ['hr_team', 'department_chief', 'branch_manager'],
    triggerSource: 'webhook',
    status: 'success',
    retryCount: 0,
    changedFields: ['status', 'hireDate', 'department'],
    storagePaths: ['/ажилтан/emp-001/ажилд-авах/2024-01-15/'],
    failureReason: null,
  },
  {
    id: 'audit-002',
    timestamp: '2024-02-01T10:15:00Z',
    employeeId: 'emp-002',
    employeeName: 'Саруул Эрдэнэ',
    action: 'add_employee',
    documentsCount: 4,
    recipientsNotified: ['hr_team', 'department_chief'],
    triggerSource: 'manual',
    status: 'success',
    retryCount: 0,
    changedFields: ['status', 'hireDate'],
    storagePaths: ['/ажилтан/emp-002/ажилд-авах/2024-02-01/'],
    failureReason: null,
  },
]

export const mockJobs: Job[] = [
  {
    id: 'job-001',
    action: 'add_employee',
    employeeId: 'emp-001',
    employeeName: 'Бат Тэмүүлэн',
    status: 'success',
    createdAt: '2024-01-15T09:28:00Z',
    completedAt: '2024-01-15T09:35:00Z',
    documentsCount: 4,
    estimatedCompletion: '2024-01-15T09:35:00Z',
  },
  {
    id: 'job-002',
    action: 'add_employee',
    employeeId: 'emp-002',
    employeeName: 'Саруул Эрдэнэ',
    status: 'processing',
    createdAt: '2024-02-01T10:10:00Z',
    completedAt: null,
    documentsCount: 4,
    estimatedCompletion: '2024-02-01T10:20:00Z',
  },
]
